cmake_minimum_required(VERSION 3.27)
project(mrm VERSION 1.0)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPERIMENTAL_CXX_MODULE_CMAKE_API "ac01f462-0f5f-432a-86aa-acef252918a6")
if(MSVC)
    add_compile_options(/W4)
else()
    add_compile_options(-Wall -Wextra -Wpedantic -fmodules-ts)
endif()
file(GLOB_RECURSE SOURCES "src/*.cpp")
add_executable(mrm ${SOURCES})

# packages
find_package(CLI11 CONFIG REQUIRED)
find_package(unofficial-libgit2 CONFIG REQUIRED)
find_package(yaml-cpp CONFIG REQUIRED)
target_link_libraries(mrm PRIVATE CLI11::CLI11)
target_link_libraries(mrm PRIVATE unofficial::libgit2::libgit2)
target_link_libraries(mrm PRIVATE yaml-cpp)

add_subdirectory(tests)
