cmake_minimum_required(VERSION 3.27)
project(multi_repo_manager VERSION 1.0)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fmodules-ts")
if(MSVC)
    add_compile_options(/W4)
else()
    add_compile_options(-Wall -Wextra -Wpedantic)
endif()
find_package(CLI11 CONFIG REQUIRED)
find_package(yaml-cpp CONFIG REQUIRED)
file(GLOB_RECURSE SOURCES "src/*.cpp")
add_executable(mrm ${SOURCES})
target_link_libraries(mrm PRIVATE CLI11::CLI11)
target_link_libraries(mrm PRIVATE yaml-cpp)
