site_name: Multi Repo Manager
site_url: https://pythys.github.io/multi-repo-manager/
site_dir: build/docs
use_directory_urls: false
copyright: Copyright &copy; Taher Alkhateeb

extra:
  generator: false

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - YAML Schema: yaml-schema.md
  - Guides:
      - Overview: guides/README.md
      - Quick Start: guides/quickstart.md
      - Best Practices: guides/best-practices.md
      - Nested Repositories: guides/nested-repos.md
      - Remote Sync & Forks: guides/remotesync-forks.md
  - Development: development.md
  - Roadmap: roadmap.md
