find_package(GTest REQUIRED)
include_directories(${CMAKE_SOURCE_DIR}/src/lib)
add_definitions(-DTEST_RESOURCES_DIR="${CMAKE_CURRENT_SOURCE_DIR}/resources")
set(UNIT_TESTS config_tests.cpp find_tests.cpp runtime_tests.cpp
               tracker_tests.cpp)
foreach(test_src ${UNIT_TESTS})
    get_filename_component(test_name ${test_src} NAME_WE)
    add_executable(${test_name} ${test_src})
    target_link_libraries(${test_name} PRIVATE GTest::gtest_main)
    target_link_libraries(${test_name} PRIVATE mrm_core)
    include(GoogleTest)
    gtest_discover_tests(${test_name} PROPERTIES LABELS unit)
endforeach()
set(INTEGRATION_TESTS sync_tests.cpp status_tests.cpp exec_tests.cpp)
foreach(test_src ${INTEGRATION_TESTS})
    get_filename_component(test_name ${test_src} NAME_WE)
    add_executable(${test_name} ${test_src})
    target_link_libraries(${test_name} PRIVATE GTest::gtest_main)
    target_link_libraries(${test_name} PRIVATE mrm_core)
    include(GoogleTest)
    gtest_discover_tests(${test_name} PROPERTIES LABELS integration)
endforeach()
